apiVersion: v1
kind: ReplicationController
metadata:
  name: myjenkins-rc
spec:
   replicas: 3
   selector: 
     app: myjenkins-rc
     version: 2.7.2
   template:
     metadata:
       labels:
          app: myjenkins-rc
          version: 2.7.2
     spec:
        containers:
        - name: myjenkins-rc-container   
          image: maha4iac/myjenkins-rc:2
          ports:
          - containerPort: 8080  